# basic options
title: WELCOME TO SAN FRANCISCO
author: Jorelle Kebeto
email: jorellekebeto@gmail.com
description: Airbnb listings optimization
github_username: jorellek

# Build settings
markdown: kramdown
theme: minima
